# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "pypy3"

install:
  - make install-poetry
  - source $HOME/.poetry/env
  - make install
  - poetry run pip freeze
  - make tox-listenvs

script:
  - make pytest
  - make lint

after_success:
  - coveralls
  # https://github.com/codecov/codecov-bash
  - bash <(curl -s https://codecov.io/bas
