# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

install:
  - pip install --upgrade pip
  - pip install nose textile docutils pygments coveralls
  - pip install .

script:
  - coverage run ./setup.py nosetests

after_success:
  - coveralls
  # https://github.com/codecov/codecov-bash
  - bash <(curl -s https://codecov.io/bash)
    
notifications:
  irc: "irc.freenode.org#pylucid"
